-- a user is said to be fake
-- if he has reviewed a business 
-- more than 2 times within one year
-- and given 5 stars
-- to it
-- , and some of his friends 
-- have also done it  
-- schema: (user_id, user_name)