-- select a neighborhood_cleansed 
-- print the top 10 users that have reviewed housings 
-- in this neighborhood after 2014-01-01
-- sort by the number of neighborhoods the user 
-- has reviewed, and then the number of reviews
-- for housings in the inputted neighborhood, 
-- and then the user_name
-- schema: (user_id, user_name, num_neighborhoods, num_reviews)